name: RUtils
version: '${version}'
main: dev.thebjoredcraft.rutils.Rutils
api-version: '1.20'
authors: [TheBjoRedCraft]
website: https://github.com/TheBjoRedCraft
commands:
  rename:
  clear:
  gamemode:
  language:
  stop:
  restart: